apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-sora-setting
spec:
  forms:
    - group: genernal
      label: 基本设置
      formSchema:
        - $formkit: text
          name: avatar
          label: 头像URL
    - group: social
      label: 社交链接
      formSchema:
        - $formkit: repeater
          name: social_media
          label: 社交媒体
          value: []
          children:
            - $formkit: select
              name: social_type
              label: 类型
              options:
                - label: 电子邮箱
                  value: email
                - label: 腾讯 QQ
                  value: qq
                - label: 新浪微博
                  value: weibo
                - label: Telegram
                  value: telegram
                - label: Facebook
                  value: facebook
                - label: Instagram
                  value: instagram
                - label: Twitter
                  value: twitter
                - label: GitHub
                  value: github
                - label: Gitee
                  value: gitee
            - $formkit: text
              name: name
              label: 名称
            - $formkit: text
              name: url
              label: 账号/地址
              validation: "required"
        - $formkit: radio
          name: RSS
          label: RSS
          value: 1
          options:
            - label: 开启
              value: 1
            - label: 关闭
              value: 0
